### ISSUE TITLE
Documentation request: upgrading to twilio 6.x

### ISSUE THREAD

**Issue by suavesav** [rdegges/django-twilio#115]
When I upgraded to twilio SDK 6.x I was met with this error from django-twilio 0.8:
`ImportError: cannot import name Verb`

The fix was simple but took a bit of digging around in the django-twilio repo.
it was to upgrade to django-twilio 0.9.0a1

Would be great to have a little note about that in the documentation. Because people are starting to adopt 6.x and it would save people some time and frustration.
I can make the PR.

**Comment by jheld** [comment]
@suavesav yes thank you. I haven't added the alpha PyPI badge (for alpha version), but maybe that's also worth doing?

By default, PyPI will not show/install alpha builds, so I appreciate you stepping up on this.

It looks like we do have some downloads of the `0.9.0a1` build. I plan on promoting it `rc` or an official `0.9.0` in the coming weeks.

**Comment by jheld** [comment]
Docs and readme have been updated. Please re-open if you want to enhance it further.
