### ISSUE TITLE
Django 2.1

### ISSUE THREAD

**Issue by ryanhiebert** [rdegges/django-twilio#139]
Django 2.1 is released, but this library's requirements explicitly require `<2.1`. This is blocking my upgrade to Django 2.1. Are there known issues with Django 2.1?

**Comment by jheld** [comment]
Hello!

Last I read the 2.1 release docs, I didn't see anything bad,  but that was
in the context of a different project.

I will open up the test run against 2.1 on a new branch. If nothing fails,
then I don't see any reason not to include the new version.

Would you be willing to run a custom wheel build and give feedback? Not
sure how comfortable you are in that flow.

**Comment by ryanhiebert** [comment]
I am able to run my test suite with the repo, if needed.

**Comment by jheld** [comment]
Merged and deployed to PyPI. Please reopen if you find any issues.
