### ISSUE TITLE
Problems with django rest framework

### ISSUE THREAD

**Issue by niko86** [rdegges/django-twilio#144]
Hello,

I've been trying to use django-twilio with DRF and nothing I do seems to get around 500 Internal Server Error.
- decorator() missing 1 required positional argument: .request_or_self()

```
@method_decorator(twilio_view, name='post')
class MessagePost(generics.CreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
```
Using django itself with django-twilio works not problem, but not with DRF.
I'm not extremely experienced with debugging issues like this, is this a problem with django-twilio or is it a DRF problem.

**Comment by niko86** [comment]
Sorted one issue now noticed another.

**Comment by jheld** [comment]
@niko86 please let me know if you have any questions.

**Comment by jheld** [comment]
@niko86 can you update us with the problem you face?

**Comment by jheld** [comment]
If I happen to run into this I will re-open, but please re-open if this issue is still occurring for you.
