### ISSUE TITLE
[Question] Why this is not avalaible for Django 2.0.x ?

### ISSUE THREAD

**Issue by nmcode** [rdegges/django-twilio#145]
[Question] Why this is not avalaible for Django 2.0 ?. What's the reasons of "incompatibility" ?

django-twilio 0.9.3 has requirement Django<2.2,>=2.1; python_version >= "3.5", but you'll have django 2.0.6 which is incompatible.

Thanks.

**Comment by jheld** [comment]
Hi @nicolasmendoza 

It's possible this is simply a bug in the setup.py syntax.

However, I do see the following there:

```
'Django>=1.8,<2.2;python_version>="3.4, <3.7"',
'Django>=2.1,<2.2;python_version>="3.5"',
```

Are you unable to install the library with your current environment setup?

**Comment by jheld** [comment]
I was trying to make it as close to the django supported environment as possible (admittedly we support a wider gamut for the short term).

https://docs.djangoproject.com/en/1.11/faq/install/#what-python-version-can-i-use-with-django

**Comment by jheld** [comment]
@nicolasmendoza ok. I'm sorry for the bug! This django 2.1 support was hard for me to get right.

I'm totally fine releasing a new build today provided we can get the syntax correct.

I wonder why travisCI didn't warn me about the build error...

Can you please share your code change as a snippet or PR?

Thanks!

**Comment by jheld** [comment]
I tried to install on my local using py3.6, and was able to install all of the requirements. I did have to explicitly reinstall django==2.0.* (2.1 comes by default via `requirements.txt` in the project), but that did work.) I was able to run the runserver in this environment.

Just so you know (I do understand that you had an install issue), this is the travis CI test that passed: https://travis-ci.org/rdegges/django-twilio/jobs/416614222

Would you be able to send over a snippet of our changes, or a PR of them? I'd be happy to quickly release a new version.

**Comment by nicolasmendoza** [comment]
@jheld Sorry for the delay, I'm "on fire" this last days but I tried to provide you a pull request soon.

Thanks!

**Comment by jheld** [comment]
@nicolasmendoza any updates? Just so we don't forget.

**Comment by jheld** [comment]
@km-pg thank you. I didn't see it was newly supported. Yes, it sure can be included!

**Comment by km-pg** [comment]
Great to hear! Thanks

**Comment by jheld** [comment]
Setup support has been added. Please reopen if 0.10.0 still has issues.
