### ISSUE TITLE
Django 2.2 Release

### ISSUE THREAD

**Issue by chris1610** [rdegges/django-twilio#151]
Django 2.2 is out now https://docs.djangoproject.com/en/2.2/releases/2.2/

If Django 2.2 is installed, Installing latest client will force downgrade to 2.1.8.

**Comment by jheld** [comment]
Please note #150 is in progress to be merged short term. 2.2 was only recently released;  hopefully we see no breakage and can simple allow the upgrade seamlessly.

**Comment by chris1610** [comment]
Oops. Sorry about that. Thanks for the quick comment! I will close this out.
