### ISSUE TITLE
Releasing a Django 2.2-compatible version of django-twilio possible?

### ISSUE THREAD

**Issue by jombooth** [rdegges/django-twilio#155]
I saw in https://github.com/rdegges/django-twilio/issues/151 and https://github.com/rdegges/django-twilio/pull/150 that the latest release candidate of `django-twilio` supports Django 2.2; but it looks like a release hasn't been cut since that rc was put up in April. Is any additional validation needed before a non-rc Django 2.2-compatible release can be made?

**Comment by jheld** [comment]
Hi @jombooth

My team will be putting the library in test this week but we are on django 2.1 still. Probably be at least a few more weeks til we upgrade. Yes please if you can test some, then I'll cut an official release. I haven't gotten any validation from the community yet.

**Comment by jombooth** [comment]
Thanks for your reply! Unfortunately since my usage of `django-twilio` is rather limited my testing wouldn't demonstrate much. So, I'll wait for the rest of the community to validate and upgrade when that happens :+1:

**Comment by jombooth** [comment]
It looks like https://github.com/rdegges/django-twilio/releases/tag/0.11.0 supports Django 2.2, so I'm gonna close this issue. :beer:

**Comment by jheld** [comment]
Oh yes I'm sorry. We went live with this and I forgot to update back here.

Thank you!
