### ISSUE TITLE
ModuleNotFoundError: No module named 'phonenumbers'

### ISSUE THREAD

**Issue by steverecio** [rdegges/django-twilio#157]
Installing django-twilio and the server throws the following error on startup:

`ModuleNotFoundError: No module named 'phonenumbers'`

I was able to fix it by adding `phonenumbers` to my requirements.txt file but maybe we should add that to the requirements file in this project. I also noticed the package requires `django-phonenumber-field==0.6` even though the latest version on pypi is 3.0.1. Maybe that should be upgraded too...

**Comment by jheld** [comment]
I haven't had the module issue. But my req file has likely included it for a long time.

There are also some deprecation warnings that I think are solved by upgrading the package. Agreed we should do so.

The django 2.2 support should be official this week -- testing has been good.

After that, yes, req/upgrades could be a good next release.

**Comment by taewookim** [comment]
is the 2.2 support out yet?

**Comment by taewookim** [comment]
Btw.. it's strange but after instsalling phone numbers via conda 

> conda install -c conda-forge phonenumbers

for some strange reason, pipen install phonenumbers does't seem to "break" (i was getting weird zlib error)

**Comment by jheld** [comment]
@taewookim yes, django 2.2 support is out. as of 0.11.0

**Comment by jheld** [comment]
#159 is supposed to fix this. Please see my question on there. I don't see anything in this repo which uses that package so I'm surprised it fails without it being installed.

**Comment by taewookim** [comment]
Are the docs updated? For [example in the docs](https://django-twilio.readthedocs.io/en/latest/views.html)

>     url(r'^hello_world/$', 'django_twilio.views.say', {
>         'text': 'Hello, world!'

This causes this error

> TypeError: view must be a callable or a list/tuple in the case of include().

**Comment by jheld** [comment]
That was merged. Closing.
