### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect data check

### ISSUE THREAD

**Issue by taewookim** [rdegges/django-twilio#160]
Django: 2.2.7
Virtualenv: Pipenv / Conda (pipenv, version 2018.05.18)

When I start django-twilio via pipenv on conda distribution, i get this error.

Any idea where im doing it wrong?

**Comment by jheld** [comment]
I've never used conda so I'm not currently a good resource for this error triage. Let me know if you'd like me to look into it further.

**Comment by taewookim** [comment]
Sorry, this error also happened on regular python shipped with Ubunu 18.04 LTS

**Comment by jheld** [comment]
Is this issue still occurring?

**Comment by jheld** [comment]
Please re-open if the problem persists.
