### ISSUE TITLE
Django-Twilio package giving me a 403 forbidden when using “twilio_view” decorator

### ISSUE THREAD

**Issue by nigelfig** [rdegges/django-twilio#175]
I'm experiencing an issue with @twilio_view I've posted the details on stackoverflow: [my question on stackoverflow](https://stackoverflow.com/questions/61059997/django-twilio-package-giving-me-a-403-forbidden-when-using-twilio-view-decorat)

**Comment by nigelfig** [comment]
When I use http://123abc.ngrok.io/newsms/ instead of https://123abc.ngrok.io/newsms/ it works. Why is that? I thought https should work with django-twilio?

**Comment by jheld** [comment]
Curious, for the `https` address, are you sure that your server is processing the request? django's runserver is not capable of https, so I want to check on that, first.

**Comment by nigelfig** [comment]
Yes, I think server is processing it, because it works when I have @csrf_exempt and use https://123abc.ngrok.io/newsms/ as webhook. I did upload an example of issue which can be duplicated to my github repository: testing-django-twilio.

**Comment by jheld** [comment]
Still researching this.

It's interesting that if you switch to `@csrf_exempt` that the request goes through, because `@twilio_view` itself is wrapped under `@csrf_exempt`.

**Comment by jheld** [comment]
I realize this next question probably isn't a good one, but in the interest of removing the simple problems first, can you put the normal decorator back in and try the https-based request again?

When you do, can you open the ngrok localhost console/panel, and check what headers were sent in on that request? I want to make sure that twilio's header actually makes it that far (that is: to your local ngrok). 

I then did a little bit of research (again, this may not be our issue, and the issue linked below may not be valid any longer, or a different issue):
https://github.com/inconshreveable/ngrok/issues/92

**Comment by nigelfig** [comment]
I was thinking about this a bit more. I had previously been using Django
2.1 and Django-Twilio version 0.10.0 and for that version I'm pretty sure
https requests were being processed correctly can you do a comparison
between the two versions of django-twilio .. to see if anything was
modified as it relates to this.

Thanks,
Nigel

**Comment by jheld** [comment]
I don't recall any real changes to the library recently. We went explicit support for py3.5-3.8, and django 2.2-3.0 but otherwise there shouldn't be any other changes yet.

Would you mind trying your test project against that older django twilio version?

**Comment by nigelfig** [comment]
So I can now confirm issue is specific to using https as webhook with ngrok, if you use http as webhook it works fine.  I have tested with earlier versions of Django and Django-Twilio, and same problem of https as webhook with ngrok not working but http working occurs.

https on my prod environment i.e not using ngrok works fine.

"can you open the ngrok localhost console/panel, and check what headers were sent in on that request"
I don't know how to check the headers, I can try to do it, if you can give me further instructions on how to. Thanks

Note my ngrok is converting http://localhost:8000 to https://123abc.ngrok.com , not sure if that is related to issue.

**Comment by jheld** [comment]
Thank you for checking on this and verifying that it's essentially an ngrok/tunneling/header issue.

When you start your ngrok server it should have a link in the terminal for you to go to localhost or 127.0.0.1 on a given port (maybe 4040? I haven't tried in awhile). If there are request history shown you can click on a request and I think on the bottom it shows the headers. If the twilio headers aren't there, then [something] clipped them off. Based on the symptoms you verified (production works, no tunneling, and earlier versions have the same issue non-production), without further evidence, I'm asserting my hypothesis to be true.

That said, there's no reason we can't update the docs to warn about https ngrok not working with the twilio security verification feature.

**Comment by jheld** [comment]
Based on the above, I'm closing the issue. Should someone run the test (check headers) and post their results, that would be beneficial. We can also reopen, but I expect we won't find any bug in this project.

Would you mind opening an issue asking for the docs change?

**Comment by incidentist** [comment]
I ran into this issue in Google App Engine, which turns https requests into http requests at the load balancer. You can fix this issue for both ngrok and App Engine by setting the SECURE_PROXY_SSL_HEADER setting in Django settings, because they both set an `X-Forwarded-Proto` header indicating the protocol of the upstream request: https://docs.djangoproject.com/en/3.2/ref/settings/#secure-proxy-ssl-header

**Comment by jheld** [comment]
@incidentist can you open an issue for a doc change and possibly a PR with the change? It would be okay to paste the django docs link as part of the change (given django likely includes more info etc and may update their docs faster than we may).
