### ISSUE TITLE
Django 3.1

### ISSUE THREAD

**Issue by ryanhiebert** [rdegges/django-twilio#180]
Django 3.1 was released August 4. This package isn't compatible, because of the version specifiers.

I believe, especially given the challenge it can be to the maintainers to keep up with everything (it's more work to release than we often think it is), that it would be wisest for the version specifier to be changed to either allowing all future versions, or at least allowing all future versions of the major release (so changing it to `<4` instead of `<3.2`). It's your package, and your decision, but that's my recommendation.

**Comment by jheld** [comment]
`0.13.1b0` is now available on PyPI. Happy to get a `0.13.1` officially released after some community feedback. Thank you.

**Comment by kolanos** [comment]
The recent change to the pip resolver is going to make this especially important:
https://github.com/pypa/pip/pull/9177
