### ISSUE TITLE
New release 0.13.1

### ISSUE THREAD

**Issue by DmytroLitvinov** [rdegges/django-twilio#190]
Hi @jheld ,

What do we need to release 0.13.1 at PyPI?
I am ready to prepare some of PRs to release it as soon as possible.

**Comment by jheld** [comment]
Has the latest prerelease worked for you? The release being alpha beta or whatever shouldn't stop you from using and upgrading Django, yes?

Nonetheless, if it works for you, I'm happy to merge.

**Comment by DmytroLitvinov** [comment]
Seems like it works :+1:

**Comment by jheld** [comment]
Thank you! I will plan to release by the end of the weekend.

**Comment by jheld** [comment]
Fresh release out on PyPI.
