### ISSUE TITLE
Support Django ASGI Requests in decompose

### ISSUE THREAD

**Issue by incidentist** [rdegges/django-twilio#195]
To reproduce:
1. Install and set up Django Channels on Django 3.1 and run an asgi server such as daphne
2. In a twilio_view, call `decompose(request)`

django-twilio throws this error:
```
<snip>
    twilio_req = decompose(req)
  File "/Users/incidentist/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django_twilio/request.py", line 44, in decompose
    "The request parameter is not a Django HttpRequest object"
django_twilio.exceptions.NotDjangoRequestException: The request parameter is not a Django HttpRequest object
```
This is because `decompose` checks that the request is of type HttpRequest or WSGIRequest. Django Channels calls views with instances of ASGIRequest, which is a valid request class in Django 3.

**Comment by jheld** [comment]
seeing as the PR was merged, closing. Please re-open if you find any issues.
