### ISSUE TITLE
Django 3.2 support

### ISSUE THREAD

**Issue by incidentist** [rdegges/django-twilio#198]
Please update the version specifiers to include Django 3.2.

**Comment by jheld** [comment]
@incidentist would you be able to test out [v0.13.2a0](https://pypi.org/project/django-twilio/0.13.2a0/)?

**Comment by nickmccullum** [comment]
@jheld we are testing out that release now.

**Comment by nickmccullum** [comment]
@jheld This works fine in our staging environment on Django 3.2. We are using it for SMS 2-factor authentication.

Do we have plans for a Django 3.3-compatible release?

**Comment by jheld** [comment]
django 4.0 but yes. Would you be open to creating a draft PR which enables the support? I can but it may take me a bit of time to get it done.

**Comment by jheld** [comment]
If you still need django 3.x support please re-open. The project is now supporting just django 4 officially but we may be able to maintain a separate branch for older releases as needed.
