### ISSUE TITLE
Django 4.0 support release date?

### ISSUE THREAD

**Issue by sknutsonsf** [rdegges/django-twilio#205]
When will support for django 4.0 be released?

The current release of django-twilio only allows django 3.2

**Comment by nickmccullum** [comment]
I'm working on upgrading a project to Django 4 using a fork of this library. I'll let you know if we run into any problems, and if not, we can merge it upstream.

**Comment by jheld** [comment]
I've merged initial django 4 support and cut the release to PyPI `0.14.0.a1`.
Closing this issue for now. If we find specific bugs related to the support of django 4.0, then we can re-open this or make new issues respectively.
You can comment here though if you don't run into any issues and I'll be happy to tag the official release.
