### ISSUE TITLE
Support for Django 4.1

### ISSUE THREAD

**Issue by aaronmader** [rdegges/django-twilio#213]
The current release of django-twilio is restricted to django 4.0

> django-twilio 0.14.0 depends on Django<4.1 and >=4.0

Is there a reason 4.1 is not supported? Anything I can do to help?

**Comment by jheld** [comment]
alpha support is up. happy to release official support soon if you find no issues!

**Comment by Afani97** [comment]
@jheld Any update on this?

**Comment by jheld** [comment]
Given no one has come forth with complaints about the alpha release, yes, seems like a good time.

I've just released it to PyPI.

**Comment by incidentist** [comment]
0.14.1 does not install via poetry with Django 4.1. I suspect the culprit is this line, which still specifies Django 4.1: https://github.com/rdegges/django-twilio/blob/master/setup.py#L14
Apologies for only noticing this after the release!

**Comment by jheld** [comment]
https://github.com/rdegges/django-twilio/releases/tag/v0.14.3

all set. thank you for checking on this.
