### ISSUE TITLE
Django 5 support

### ISSUE THREAD

**Issue by nickmccullum** [rdegges/django-twilio#238]
Does this project have any plans to add support for Django 5?

**Comment by calebsyring** [comment]
It looks like 5.0 support was added in https://github.com/rdegges/django-twilio/pull/239. Was there any reason why it was pinned to <=5.0 specifically (vs 5.*)? This is keeping me from upgrading the patch version. [Django 5.0 has a couple CVEs out](https://docs.djangoproject.com/en/5.0/releases/security/), and `pip-audit` is complaining.

**Comment by jheld** [comment]
No specific reason. Happy to accept a PR!

**Comment by smaccona** [comment]
@jheld can you make a release that incorporates this change? Anyone on Django 5.2 or higher will run into deployment issues unless they use a workaround like above. Thanks!
