### ISSUE TITLE
Django 1.9 deprication warnings

### ISSUE THREAD

**Issue by catskul** [rdegges/django-twilio#87]
```
.../env/local/lib/python2.7/site-packages/django_twilio/models.py:15: 
RemovedInDjango19Warning: Model class django_twilio.models.Caller doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Caller(models.Model):

.../env/local/lib/python2.7/site-packages/django_twilio/models.py:36: 
RemovedInDjango19Warning: Model class django_twilio.models.Credential doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Credential(models.Model):
```

**Comment by joshlsullivan** [comment]
I get the same issue.

/Users/joshsullivan/.virtualenvs/django-twilio/lib/python2.7/site-packages/django_twilio/models.py:15: RemovedInDjango19Warning: Model class django_twilio.models.Caller doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Caller(models.Model):

/Users/joshsullivan/.virtualenvs/django-twilio/lib/python2.7/site-packages/django_twilio/models.py:36: RemovedInDjango19Warning: Model class django_twilio.models.Credential doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Credential(models.Model):

/Users/joshsullivan/.virtualenvs/django-twilio/lib/python2.7/site-packages/django_twilio/utils.py:69: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  caller = Caller.objects.get(phone_number=request.REQUEST['From'])

/Users/joshsullivan/.virtualenvs/django-twilio/lib/python2.7/site-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)

**Comment by catskul** [comment]
I was able to get this to go away by adding it to INSTALLED_APPS
