### ISSUE TITLE
Saving to Callers

### ISSUE THREAD

**Issue by joshlsullivan** [rdegges/django-twilio#91]
I am writing a script that will take the `From` number and save it to the database. I would like to save it to the Callers database in the admin. Is that possible?

**Comment by jheld** [comment]
I'll try to think on this a bit more, but do you remember some specifics of what the flow was supposed to be, involving the django admin?

**Comment by joshlsullivan** [comment]
@jheld You can mark this as closed. I no longer need this. Thanks for responding.
