### ISSUE TITLE
Support later versions of Django

### ISSUE THREAD

**Issue by km-pg** [rdegges/django-twilio#94]
Getting a warning in Django 1.8 about request.REQUEST being removed in 1.9

site-packages/django_twilio/utils.py:69: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  caller = Caller.objects.get(phone_number=request.REQUEST['From'])

**Comment by nsomaru** [comment]
@phalt is this project still maintained?

**Comment by rdegges** [comment]
Hey guys, this project is PARTIALLY maintained right now.

It would be awesome to get some help.

I'm the original author, but am not working on any active django + twilio projects lately, so I've been neglecting this. @phalt was maintaining for a long time, but recently left Twilio, and likely doesn't have a lot of free time ton contribute.

If anyone wants to help out, I'll still review / merge PRs, and keep cutting releases. <3

**Comment by nsomaru** [comment]
@rdegges

If you don't mind mentoring a noob, I could pick up some of the slack.

**Comment by rdegges** [comment]
Heyo! I'd love to do that, but don't really have the time to mentor right now. My work and personal life is sort of crazy :( But if you send over a PR I'm happy to review!

**Comment by lggwettmann** [comment]
Pity this package is unmaintained and not working in Django > 1.09. Looks like a great package (and like it was a lot of work).

**Comment by rdegges** [comment]
I feel bad :( I'd love to work on this, but don't really use Django much now-a-days, so am really out of the loop on what I'd need to do to make this awesome without investing a ton of time.

If anyone wants to jump in and contribute, I'm 100% open! I believe 99% of this code is still good to go, with some minor changes needed for Django release modifications over the last couple years.

**Comment by km-pg** [comment]
@rdegges Can you review this PR? Might be a step in the right direction.
https://github.com/rdegges/django-twilio/pull/95

**Comment by wbt** [comment]
@rdegges maybe also [#131](https://github.com/govtrack/govtrack.us-web/pull/131)?

**Comment by jheld** [comment]
Hi all,

I'm the new maintainer, though I'm surely open to PRs and help.

I'm getting the project prepared for upgrades and a new release soon.

**Comment by jheld** [comment]
master and 0.9.0 address this.

Please re-open if you encounter any issues.
